site_name: Laughtart
site_url: https://Dollor-Lua.github.io/laughtart

nav:
    - Home: index.md
    - Docs:
          - Home: docs.md
          - Functions: docs.md
          - Classes: docs.md
          - Variables: docs.md
    - Tutorial:
          - Basics: docs.md
          - Creating Variables: docs.md
          - Creating Functions: docs.md
          - Creating Classes: docs.md

theme:
    name: material
    favicon: "imgs/icon512x512.png"
    logo: "imgs/laughtartblackandwhite.png"
    palette:
        primary: black
        accent: grey
    highlightjs: true

extra_css:
    - stylesheets/dark_theme.css
